//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P3Image.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Campos
    {
        public Campos()
        {
            this.Lista = new HashSet<Lista>();
        }
    
        public int Codigo { get; set; }
        public int CodigoSubCategoria { get; set; }
        public int Ordem { get; set; }
        public string Descricao { get; set; }
        public string Tipo { get; set; }
        public bool Ativo { get; set; }
    
        public virtual SubCategoria SubCategoria { get; set; }
        public virtual ICollection<Lista> Lista { get; set; }
    }
}
