//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P3Image.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubCategoria
    {
        public SubCategoria()
        {
            this.Campos = new HashSet<Campos>();
        }
    
        public int Codigo { get; set; }
        public int CodigoCategoria { get; set; }
        public string Descricao { get; set; }
        public string Slug { get; set; }
        public bool Ativo { get; set; }
    
        public virtual ICollection<Campos> Campos { get; set; }
        public virtual Categoria Categoria { get; set; }
    }
}
